src/Entity/Location.php
<?php

namespace App\Entity;

use App\Repository\LocationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: LocationRepository::class)]
class Location
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $city = null;

    #[ORM\Column(length: 2)]
    private ?string $country_code = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 8)]
    private ?string $latitude = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 8)]
    private ?string $longitude = null;

    #[ORM\OneToMany(mappedBy: 'location', targetEntity: Measurement::class)]
    private Collection $measurements;

    public function __construct()
    {
        $this->measurements = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getCountryCode(): ?string
    {
        return $this->country_code;
    }

    public function setCountryCode(string $country_code): self
    {
        $this->country_code = $country_code;

        return $this;
    }

    public function getLatitude(): ?string
    {
        return $this->latitude;
    }

    public function setLatitude(string $latitude): self
    {
        $this->latitude = $latitude;

        return $this;
    }

    public function getLongitude(): ?string
    {
        return $this->longitude;
    }

    public function setLongitude(string $longitude): self
    {
        $this->longitude = $longitude;

        return $this;
    }

    /**
     * @return Collection<int, Measurement>
     */
    public function getMeasurements(): Collection
    {
        return $this->measurements;
    }

    public function addMeasurement(Measurement $measurement): self
    {
        if (!$this->measurements->contains($measurement)) {
            $this->measurements->add($measurement);
            $measurement->setLocation($this);
        }

        return $this;
    }

    public function removeMeasurement(Measurement $measurement): self
    {
        if ($this->measurements->removeElement($measurement)) {
            // set the owning side to null (unless already changed)
            if ($measurement->getLocation() === $this) {
                $measurement->setLocation(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return (string) $this->getId().' '.$this->getCity();
    }
}

src/Form/LocationType.php
<?php

namespace App\Form;

use App\Entity\Location;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class LocationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('city')
            ->add('country_code', ChoiceType::class, [
                'choices' => [
                    'Polska -> PL' => 'PL',
                    'Niemcy -> DE' => 'DE',
                    'Hiszpania -> ES' => 'ES',
                ],])
            ->add('latitude')
            ->add('longitude');
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Location::class,
        ]);
    }
}

src/Controller/LocationController.php
<?php

namespace App\Controller;

use App\Entity\Location;
use App\Form\LocationType;
use App\Repository\LocationRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/location')]
class LocationController extends AbstractController
{
    #[Route('/', name: 'app_location_index', methods: ['GET'])]
    #[IsGranted('ROLE_LOCATION_INDEX')]
    public function index(LocationRepository $locationRepository): Response
    {
        return $this->render('location/index.html.twig', [
            'locations' => $locationRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_location_new', methods: ['GET', 'POST'])]
    #[IsGranted('ROLE_LOCATION_NEW')]
    public function new(Request $request, LocationRepository $locationRepository): Response
    {
        $location = new Location();
        $form = $this->createForm(LocationType::class, $location, ['validation_groups' => ['new']]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $locationRepository->save($location, true);

            return $this->redirectToRoute('app_location_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('location/new.html.twig', [
            'location' => $location,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_location_show', methods: ['GET'])]
    #[IsGranted('ROLE_LOCATION_SHOW')]
    public function show(Location $location): Response
    {
        return $this->render('location/show.html.twig', [
            'location' => $location,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_location_edit', methods: ['GET', 'POST'])]
    #[IsGranted('ROLE_LOCATION_EDIT')]
    public function edit(Request $request, Location $location, LocationRepository $locationRepository): Response
    {
        $form = $this->createForm(LocationType::class, $location, ['validation_groups' => ['edit']]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $locationRepository->save($location, true);

            return $this->redirectToRoute('app_location_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('location/edit.html.twig', [
            'location' => $location,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_location_delete', methods: ['POST'])]
    #[IsGranted('ROLE_LOCATION_DELETE')]
    public function delete(Request $request, Location $location, LocationRepository $locationRepository): Response
    {
        if ($this->isCsrfTokenValid('delete' . $location->getId(), $request->request->get('_token'))) {
            $locationRepository->remove($location, true);
        }

        return $this->redirectToRoute('app_location_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/location/_delete_form.html.twig
{% if is_granted('ROLE_LOCATION_DELETE') %}

<form method="post" action="{{ path('app_location_delete', {'id': location.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ location.id) }}">
    <button class="btn">Delete</button>
</form>

{% endif %}

templates/location/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    {% if is_granted('ROLE_LOCATION_NEW') %}
    <button class="btn">{{ button_label|default('Save') }}</button>
    {% endif %}
{{ form_end(form) }}

templates/location/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Location{% endblock %}

{% block body %}
    <h1>Edit Location</h1>

    {{ include('location/_form.html.twig', {'button_label': 'Update'}) }}

    {% if is_granted('ROLE_LOCATION_INDEX') %}
    <a href="{{ path('app_location_index') }}">back to list</a>
    {% endif %}

    {{ include('location/_delete_form.html.twig') }}
{% endblock %}

templates/location/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Location index{% endblock %}

{% block body %}
    <h1>Location index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>City</th>
                <th>Country_code</th>
                <th>Latitude</th>
                <th>Longitude</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for location in locations %}
            <tr>
                <td>{{ location.id }}</td>
                <td>{{ location.city }}</td>
                <td>{{ location.countryCode }}</td>
                <td>{{ location.latitude }}</td>
                <td>{{ location.longitude }}</td>
                <td>
                    {% if is_granted('ROLE_LOCATION_SHOW') %}
                    <a href="{{ path('app_location_show', {'id': location.id}) }}">show</a>
                    {% endif %}

                    {% if is_granted('ROLE_LOCATION_EDIT') %}
                    <a href="{{ path('app_location_edit', {'id': location.id}) }}">edit</a>
                    {% endif %}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% if is_granted('ROLE_LOCATION_NEW') %}
    <a href="{{ path('app_location_new') }}">Create new</a>
    {% endif %}
{% endblock %}

templates/location/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Location{% endblock %}

{% block body %}
    <h1>Create new Location</h1>

    {{ include('location/_form.html.twig') }}

    {% if is_granted('ROLE_LOCATION_INDEX') %}
    <a href="{{ path('app_location_index') }}">back to list</a>
    {% endif %}

{% endblock %}

templates/location/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Location{% endblock %}

{% block body %}
    <h1>Location</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ location.id }}</td>
            </tr>
            <tr>
                <th>City</th>
                <td>{{ location.city }}</td>
            </tr>
            <tr>
                <th>Country_code</th>
                <td>{{ location.countryCode }}</td>
            </tr>
            <tr>
                <th>Latitude</th>
                <td>{{ location.latitude }}</td>
            </tr>
            <tr>
                <th>Longitude</th>
                <td>{{ location.longitude }}</td>
            </tr>
        </tbody>
    </table>

    {% if is_granted('ROLE_LOCATION_INDEX') %}
    <a href="{{ path('app_location_index') }}">back to list</a>
    {% endif %}

    {% if is_granted('ROLE_LOCATION_EDIT') %}
    <a href="{{ path('app_location_edit', {'id': location.id}) }}">edit</a>
    {% endif %}

    {{ include('location/_delete_form.html.twig') }}
{% endblock %}