src/Entity/Measurement.php
<?php

namespace App\Entity;

use App\Repository\MeasurementRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MeasurementRepository::class)]
class Measurement
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'measurements')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Location $location = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $datetime = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 8)]
    private ?string $temperature = null;

    #[ORM\Column(length: 255)]
    private ?string $description = null;

    #[ORM\Column]
    private ?int $emoji_id = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLocation(): ?Location
    {
        return $this->location;
    }

    public function setLocation(?Location $location): self
    {
        $this->location = $location;

        return $this;
    }

    public function getDatetime(): ?\DateTimeInterface
    {
        return $this->datetime;
    }

    public function setDatetime(\DateTimeInterface $datetime): self
    {
        $this->datetime = $datetime;

        return $this;
    }

    public function getTemperature(): ?string
    {
        return $this->temperature;
    }

    public function setTemperature(string $temperature): self
    {
        $this->temperature = $temperature;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getEmojiId(): ?int
    {
        return $this->emoji_id;
    }

    public function setEmojiId(int $emoji_id): self
    {
        $this->emoji_id = $emoji_id;

        return $this;
    }

    public function __toString()
    {
        return (string) $this->getLocation().'|'.$this->getDatetime()->format('d.m.Y').'|'.$this->getTemperature().'|'.$this->getDescription();
    }
}

src/Form/MeasurementType.php
<?php

namespace App\Form;

use App\Entity\Measurement;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MeasurementType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('datetime')
            ->add('temperature')
            ->add('description')
            ->add('emoji_id', ChoiceType::class, [
                'choices' => [
                    'Słonce -> 1' => 1,
                    'Słońce za chmurami -> 2' => 2,
                    'Pochmurnie -> 3' => 3,
                    'Opad deszczu -> 4' => 4,
                    'Burza -> 5' => 5,
                    'Opad śniegu -> 6' => 6,
                    'Mgła -> 7' => 7,
                ],])
            ->add('location')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Measurement::class,
        ]);
    }
}

src/Controller/MeasurementController.php
<?php

namespace App\Controller;

use App\Entity\Measurement;
use App\Form\MeasurementType;
use App\Repository\MeasurementRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/measurement')]
class MeasurementController extends AbstractController
{
    #[Route('/', name: 'app_measurement_index', methods: ['GET'])]
    #[IsGranted('ROLE_MEASUREMENT_INDEX')]
    public function index(MeasurementRepository $measurementRepository): Response
    {
        return $this->render('measurement/index.html.twig', [
            'measurements' => $measurementRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_measurement_new', methods: ['GET', 'POST'])]
    #[IsGranted('ROLE_MEASUREMENT_NEW')]
    public function new(Request $request, MeasurementRepository $measurementRepository): Response
    {
        $measurement = new Measurement();
        $form = $this->createForm(MeasurementType::class, $measurement, ['validation_groups' => ['new']]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $measurementRepository->save($measurement, true);

            return $this->redirectToRoute('app_measurement_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('measurement/new.html.twig', [
            'measurement' => $measurement,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_measurement_show', methods: ['GET'])]
    #[IsGranted('ROLE_MEASUREMENT_SHOW')]
    public function show(Measurement $measurement): Response
    {
        return $this->render('measurement/show.html.twig', [
            'measurement' => $measurement,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_measurement_edit', methods: ['GET', 'POST'])]
    #[IsGranted('ROLE_MEASUREMENT_EDIT')]
    public function edit(Request $request, Measurement $measurement, MeasurementRepository $measurementRepository): Response
    {
        $form = $this->createForm(MeasurementType::class, $measurement, ['validation_groups' => ['edit']]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $measurementRepository->save($measurement, true);

            return $this->redirectToRoute('app_measurement_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('measurement/edit.html.twig', [
            'measurement' => $measurement,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_measurement_delete', methods: ['POST'])]
    #[IsGranted('ROLE_MEASUREMENT_DELETE')]
    public function delete(Request $request, Measurement $measurement, MeasurementRepository $measurementRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$measurement->getId(), $request->request->get('_token'))) {
            $measurementRepository->remove($measurement, true);
        }

        return $this->redirectToRoute('app_measurement_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/measurement/_delete_form.html.twig
{% if is_granted('ROLE_MEASUREMENT_DELETE') %}

<form method="post" action="{{ path('app_measurement_delete', {'id': measurement.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ measurement.id) }}">
    <button class="btn">Delete</button>
</form>

{% endif %}

templates/measurement/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    {% if is_granted('ROLE_MEASUREMENT_NEW') %}
    <button class="btn">{{ button_label|default('Save') }}</button>
    {% endif %}
{{ form_end(form) }}

templates/measurement/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Measurement{% endblock %}

{% block body %}
    <h1>Edit Measurement</h1>

    {{ include('measurement/_form.html.twig', {'button_label': 'Update'}) }}

    {% if is_granted('ROLE_MEASUREMENT_INDEX') %}
    <a href="{{ path('app_measurement_index') }}">back to list</a>
    {% endif %}

    {{ include('measurement/_delete_form.html.twig') }}
{% endblock %}

templates/measurement/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>Measurement index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Datetime</th>
                <th>Temperature</th>
                <th>Description</th>
                <th>Emoji_id</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for measurement in measurements %}
            <tr>
                <td>{{ measurement.id }}</td>
                <td>{{ measurement.datetime ? measurement.datetime|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ measurement.temperature }}</td>
                <td>{{ measurement.description }}</td>
                <td>{{ measurement.emojiId }}</td>
                <td>
                    {% if is_granted('ROLE_MEASUREMENT_SHOW') %}
                    <a href="{{ path('app_measurement_show', {'id': measurement.id}) }}">show</a>
                    {% endif %}

                    {% if is_granted('ROLE_MEASUREMENT_EDIT') %}
                    <a href="{{ path('app_measurement_edit', {'id': measurement.id}) }}">edit</a>
                    {% endif %}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {% if is_granted('ROLE_MEASUREMENT_NEW') %}
    <a href="{{ path('app_measurement_new') }}">Create new</a>
    {% endif %}
{% endblock %}

templates/measurement/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Measurement{% endblock %}

{% block body %}
    <h1>Create new Measurement</h1>

    {{ include('measurement/_form.html.twig') }}

    {% if is_granted('ROLE_MEASUREMENT_INDEX') %}
    <a href="{{ path('app_measurement_index') }}">back to list</a>
    {% endif %}

{% endblock %}

templates/measurement/show.html.twig
{% extends 'base.html.twig' %}


{% block title %}Measurement{% endblock %}

{% block body %}
    <h1>Measurement</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ measurement.id }}</td>
            </tr>
            <tr>
                <th>Datetime</th>
                <td>{{ measurement.datetime ? measurement.datetime|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Temperature</th>
                <td>{{ measurement.temperature }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ measurement.description }}</td>
            </tr>
            <tr>
                <th>Emoji_id</th>
                <td>{{ measurement.emojiId }}</td>
            </tr>
        </tbody>
    </table>

    {% if is_granted('ROLE_MEASUREMENT_INDEX') %}
    <a href="{{ path('app_measurement_index') }}">back to list</a>
    {% endif %}

    {% if is_granted('ROLE_MEASUREMENT_EDIT') %}
    <a href="{{ path('app_measurement_edit', {'id': measurement.id}) }}">edit</a>
    {% endif %}

    {{ include('measurement/_delete_form.html.twig') }}
{% endblock %}